---
name: fas
services:
  frontend:
    build:
      context: . # Current directory
      dockerfile: Dockerfile
    container_name: fas-frontend
    ports:
      - "5173:80" # Map host port 5173 to container's Nginx port 80
